# LazyTables Dark Theme

name = "LazyDark"
author = "LazyTables Team"

[colors]
# Core UI colors
background = "#0d0d0d"
foreground = "#cdd6f4"
text = "#ffffff"
selection_bg = "#45475a"
cursor = "#f5e0dc"

# Pane colors
pane_background = "#181825"
border = "#313244"
active_border = "#74c7ec"
inactive_pane = "#45475a"

# Component colors
header_fg = "#cba6f7"
status_bg = "#313244"
status_fg = "#cdd6f4"
primary_highlight = "#74c7ec"

# Table colors
table_header_bg = "#313244"
table_header_fg = "#cba6f7"
table_row_bg = "#181825"
table_row_alt_bg = "#1e1e2e"
selected_cell_bg = "#45475a"

# Modal colors
modal_bg = "#0d0d0d"
modal_border = "#74c7ec"
modal_title = "#74c7ec"

# Input field colors
input_bg = "#1e1e2e"
input_fg = "#ffffff"
input_border = "#45475a"
input_active_border = "#74c7ec"
input_placeholder = "#6c7086"

# Button colors
button_bg = "#0000ff"
button_fg = "#000000"
button_active_bg = "#74c7ec"
button_active_fg = "#000000"

# Status colors
success = "#00ff00"
error = "#ff0000"
warning = "#ffff00"
info = "#00ffff"

# SQL editor colors
editor_bg = "#1e1e2e"
editor_fg = "#cdd6f4"
editor_line_number = "#6c7086"
editor_cursor_line = "#313244"
editor_selection = "#45475a"

# Syntax highlighting
syntax_keyword = "#cba6f7"
syntax_string = "#a6e3a1"
syntax_number = "#fab387"
syntax_comment = "#6c7086"
syntax_function = "#89b4fa"
syntax_operator = "#f5c2e7"

# Toast colors
toast_success_bg = "#285028"
toast_error_bg = "#502828"
toast_warning_bg = "#505028"
toast_info_bg = "#283c50"

# Help colors
help_bg = "#1e1e2e"
help_fg = "#cdd6f4"
help_header = "#cba6f7"
help_key = "#74c7ec"
help_description = "#bac2de"